version: '3.4'

services:
  react_nginx:
    image: jamessmith52963/basic-react:build-latest
    ports:
      - 82:80
    deploy:
      replicas: 1
      restart_policy: 
        condition: any
      placement:
        constraints:
           - node.role == worker
